change the format in index.html
MengdieZhang/software-product-sprint pull request #5
Opened 2022-06-11 11:51 UTC by MengdieZhang

2022-06-13 15:25 UTC, estefanytorres approved these changes
LGTM!

2022-06-16 15:46 UTC, MengdieZhang commented
complete week3 tasks

2022-06-16 18:51 UTC, estefanytorres requested changes

2022-06-16 18:51 UTC, estefanytorres commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +//import org.jsoup.safety.Whitelist;
Did you mean to leave this comment?

2022-06-16 18:51 UTC, estefanytorres commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +    //String textValue = Jsoup.clean(request.getParameter("title"), Whitelist.none());
Did you mean to leave this comment?

2022-06-16 18:51 UTC, estefanytorres commented on portfolio/src/main/java/com/google/sps/data/Message.java
> +/** An item on a todo list. */
I feel like this comment is a little confusing because it is not part of a todo list, can you update the description comment?

2022-06-16 18:51 UTC, estefanytorres commented on portfolio/src/main/webapp/script.js
> +/*
Did you mean to leave this comment here?

2022-06-16 18:51 UTC, estefanytorres commented on portfolio/src/main/webapp/script.js
> +    fetch('/delete-task', {method: 'POST', body: params});
research about the DELETE method, it would be more appropriate for this task

2022-06-16 18:52 UTC, estefanytorres commented
Great job! I'm really impressed by all the progress you've made, please make sure to clean up (most my comments are just reminders to remove or update comments). please fix and re-request my review, and remember to make any other changes (unrelated to the comments) in a new branch/PR

2022-06-17 05:35 UTC, MengdieZhang commented
> Great job! I'm really impressed by all the progress you've made, please make sure to clean up (most my comments are just reminders to remove or update comments). please fix and re-request my review, and remember to make any other changes (unrelated to the comments) in a new branch/PR

So many thanks for your feedback~. I have submitted a new PR

2022-06-17 15:21 UTC, estefanytorres commented on portfolio/src/main/webapp/script.js
> +    fetch('/delete-task', {method: 'POST', body: params});
I would prefer not to merge this comment to main, typically main is very clean code, you can keep this in a separate branch if you want to keep it for future development

2022-06-17 15:23 UTC, estefanytorres requested changes
Hi! I think maybe I didn't explain myself about. further changes in the same PR. You can address comments on the same branch/PR but if I give my approval without any change requests then you should merge to main. You can have multiple pr open, but for this case where the changes are related you should do on the same PR and request review. We can go over it on our 1:1 if you still have questions

2022-06-17 15:25 UTC, estefanytorres commented on portfolio/src/main/webapp/script.js
> +  /** Tells the server to delete the message.
I would prefer not to merge this comment to main, typically main is very clean code, you can keep this in a separate branch if you want to keep it for future development

2022-06-21 14:16 UTC, estefanytorres requested changes

2022-06-21 14:16 UTC, estefanytorres commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +//import org.jsoup.safety.Whitelist;
Please remove this comment

2022-06-21 14:16 UTC, estefanytorres commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +    //String textValue = Jsoup.clean(request.getParameter("title"), Whitelist.none());
Please remove this comment

2022-06-21 16:33 UTC, estefanytorres approved these changes
Great job!! thanks for taking care of small review requests

2022-06-22 02:24 UTC, MengdieZhang commented
Merge week3's work to main

2022-06-22 02:24 UTC, merged